### ISSUE TITLE
Handle null consistency with Vue 

### ISSUE THREAD

**Issue by 304NotModified** [chairuosen/vue2-ace-editor#27]
This is a discussion related to #22

Currently there is a crash when the `v-model` is `null`. This is unexpected as when using a plain `<textarea>` with vue and `v-model` just works when the `v-model` is `null`. See [fiddle](https://jsfiddle.net/p3g99g16/).

Why do we need a crash in this lib for `null`? Why isn't consistent with Vue itself?

related #2

**Comment by Sequoya42** [comment]
Hello, any news on this?
I have the same trouble with an empty string.
If my string is even only one space, everything works fine.
But if it's empty, it does not toggle correctly.

**Comment by chairuosen** [comment]
hi @Sequoya42 
your problem is not same as this issue.
This issue is talking about if it is necessary to support null of v-model.

You mean passing "" causes error ?
Try [this demo](https://github.com/chairuosen/vue-ace-editor-demo/tree/vue2) 
does it work?

**Comment by Sequoya42** [comment]
It does work.
The error came from a weird need I had, where I had tabs, and could toggle the value.
<editor v-model="foo[bar]"> 
With 
```
foo {
one: "stuff",
two: ""
}
```
And toggling bar to either one or two, the problem arise. 
I use a different technique and made a wrapper component, and do not have this problem anymore since I'll make an editor per tab.
 [and now I get a warning `Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message` , but that's another issue].

Thank you for clarifying.

**Comment by chairuosen** [comment]
@Sequoya42 Thanks man. This is a bug and is fixed now. plz reinstall the latest version
