### ISSUE TITLE
UTC time conversion not working

### ISSUE THREAD

**Issue by Soumi95** [chairuosen/vue2-ace-editor#95]
Hi
I have to use UTC date and time of a specific date and time in my project. But UTC conversion for specific date and time is not happening in this editor. When I am trying to get current date time through Date object, it is giving me UTC date and time but when I am trying to get UTC for specific date and time through Date object, it is not coming. 

Could you please suggest any solution or why this is happening?

Thanking you in advance.

**Comment by chairuosen** [comment]
i don't know what is the relation of `editor` and `UTC conversion`.    it is just a text editor, not a date util.

please show me some code for more detail?

**Comment by Soumi95** [comment]
When I checked 

const date = new Date() and console.log(date)
it is giving => 2023-03-02T06:23:08.616Z
which is UTC time, not my local time.

But when I am giving 
const date = new Date('2023-02-28 10:00') and console.log(date)
it is giving => 2023-02-28T10:00:00.000Z
Then I am trying to get date.getUTCHours() and it is giving 10 which is not correct.

This is the scenario.

**Comment by chairuosen** [comment]
this is a basic javascript problem. not about the editor.

I think the reason is when you create Date with string param like `2023-02-28 10:00` ,it is not a absolute time, it cannot point to a unix timestamp. so different javascript environment uses different default timezone to fix it to a absolute time. In my Chrome it will fix it to a GMT time. or in your computer it is a UTC time. 
so, create Date with timezone suffix will help you, maybe.
